env:
  LANG: en_US.utf8
  MAVEN_OPTS: -Xmx2048m -Xms1024m
jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven on Java ${{ matrix.java }}
      run: mvn -B -V -DskipAssembly verify --no-transfer-progress
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
        - '21'
name: Java Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
permissions: read-all
