env:
  LANG: en_US.utf8
  MAVEN_OPTS: -Xmx2048m -Xms1024m
jobs:
  sonarcloud:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    name: Scan
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      run: mvn -B -V -Pcoverage -DskipAssembly verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        --no-transfer-progress
name: SonarCloud
on:
  repository_dispatch:
    types: trigger-ga___sonar.yml
permissions: read-all
